apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-app
  labels:
    app: go-example
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: go-example-app
  template:
    metadata:
      labels:
        app: go-example-app
    spec:
      containers:
      - name: go-example-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: go-example-app
spec:
  selector:
    app: go-example-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000