name: Package and Upload Helm Chart Release

on:
  push:
    branches:
    - main
    paths:
    - helm/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(cat helm/go-deploy-example/Chart.yaml | grep version | awk '{print $2}')
    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.13.0
    - name: Package Helm Chart
      run: |
        helm package helm/go-deploy-example -d .helm-charts
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Helm Chart
      run: |
        helm push .helm-charts/go-deploy-example-${{ steps.get_version.outputs.VERSION }}.tgz oci://ghcr.io/sunu/go-deploy-example:${{ steps.get_version.outputs.VERSION }}
      