name: Builds and pushes Docker Images and Helm charts to Github Registry

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install chart publishing dependencies (chartpress, helm)
      run: |
        pip install chartpress
        pip list

        helm version

    - name: Build and push Docker image
      run: |
        chartpress --push