name: Builds and pushes Docker Images and Helm charts to Github Registry

on:
  push:
    branches:
    - main
    tags:
    - "**"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install chart publishing dependencies (chartpress, helm)
      run: |
        pip install chartpress
        pip list

        helm version

    - name: Build and push Docker image. Update the image tag, chart version etc as needed
      run: |
        cd helm && chartpress --push

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(cat helm/go-deploy-example/Chart.yaml | grep version | awk '{print $2}')

    - name: Package Helm Chart
      run: |
        helm package helm/go-deploy-example -d .helm-charts

    - name: Push Helm Chart
      run: |
        helm push .helm-charts/go-deploy-example-helm-chart-${{ steps.get_version.outputs.VERSION }}.tgz oci://ghcr.io/sunu/go-deploy-example
